/* @page reg-init.c
 *       PLC411::RTE
 *       Registers :: API (Init.)
 *       2022, atgroup09@gmail.com
 */

#include "reg-init.h"


REG_SysStat1_Pack_ut PLC_SYS_STAT1;


/** @brief  Init. registers.
 *  @param  None.
 *  @return The number of inited registers.
 */
uint16_t REG_Init(void)
{
    uint16_t Res = 0;

    //clear register memory
    REG_Clear();

    //DI
    Res += REG_InitRegs(REG_DI_NORM_VAL__GID, REG_DI_NORM_VAL__ZONE, REG_DI_NORM_VAL__TYPESZ, REG_DI_NORM_VAL__GROUP, REG_DI_NORM_VAL__TYPE, REG_DI_NORM_VAL__POS, REG_DI_NORM_VAL__SZ, REG_DI_NORM_VAL__SADDR, REG_DI_NORM_VAL__MBTABLE, REG_DI_NORM_VAL__MBPOS, REG_DI_NORM_VAL__A00, REG_DI_NORM_VAL__A01, REG_DI_NORM_VAL__A02, REG_DI_NORM_VAL__DTABLE, REG_DI_NORM_VAL__DPOS, REG_DI_NORM_VAL__RETAIN, REG_DI_NORM_VAL__STR);
    Res += REG_InitRegs(REG_DI_TACH_VAL__GID, REG_DI_TACH_VAL__ZONE, REG_DI_TACH_VAL__TYPESZ, REG_DI_TACH_VAL__GROUP, REG_DI_TACH_VAL__TYPE, REG_DI_TACH_VAL__POS, REG_DI_TACH_VAL__SZ, REG_DI_TACH_VAL__SADDR, REG_DI_TACH_VAL__MBTABLE, REG_DI_TACH_VAL__MBPOS, REG_DI_TACH_VAL__A00, REG_DI_TACH_VAL__A01, REG_DI_TACH_VAL__A02, REG_DI_TACH_VAL__DTABLE, REG_DI_TACH_VAL__DPOS, REG_DI_TACH_VAL__RETAIN, REG_DI_TACH_VAL__STR);
    Res += REG_InitRegs(REG_DI_TACH_SETPOINT__GID, REG_DI_TACH_SETPOINT__ZONE, REG_DI_TACH_SETPOINT__TYPESZ, REG_DI_TACH_SETPOINT__GROUP, REG_DI_TACH_SETPOINT__TYPE, REG_DI_TACH_SETPOINT__POS, REG_DI_TACH_SETPOINT__SZ, REG_DI_TACH_SETPOINT__SADDR, REG_DI_TACH_SETPOINT__MBTABLE, REG_DI_TACH_SETPOINT__MBPOS, REG_DI_TACH_SETPOINT__A00, REG_DI_TACH_SETPOINT__A01, REG_DI_TACH_SETPOINT__A02, REG_DI_TACH_SETPOINT__DTABLE, REG_DI_TACH_SETPOINT__DPOS, REG_DI_TACH_SETPOINT__RETAIN, REG_DI_TACH_SETPOINT__STR);
    Res += REG_InitRegs(REG_DI_TACH_SETPOINT_ALLOW__GID, REG_DI_TACH_SETPOINT_ALLOW__ZONE, REG_DI_TACH_SETPOINT_ALLOW__TYPESZ, REG_DI_TACH_SETPOINT_ALLOW__GROUP, REG_DI_TACH_SETPOINT_ALLOW__TYPE, REG_DI_TACH_SETPOINT_ALLOW__POS, REG_DI_TACH_SETPOINT_ALLOW__SZ, REG_DI_TACH_SETPOINT_ALLOW__SADDR, REG_DI_TACH_SETPOINT_ALLOW__MBTABLE, REG_DI_TACH_SETPOINT_ALLOW__MBPOS, REG_DI_TACH_SETPOINT_ALLOW__A00, REG_DI_TACH_SETPOINT_ALLOW__A01, REG_DI_TACH_SETPOINT_ALLOW__A02, REG_DI_TACH_SETPOINT_ALLOW__DTABLE, REG_DI_TACH_SETPOINT_ALLOW__DPOS, REG_DI_TACH_SETPOINT_ALLOW__RETAIN, REG_DI_TACH_SETPOINT_ALLOW__STR);
    Res += REG_InitRegs(REG_DI_TACH_SETPOINT_REACHED__GID, REG_DI_TACH_SETPOINT_REACHED__ZONE, REG_DI_TACH_SETPOINT_REACHED__TYPESZ, REG_DI_TACH_SETPOINT_REACHED__GROUP, REG_DI_TACH_SETPOINT_REACHED__TYPE, REG_DI_TACH_SETPOINT_REACHED__POS, REG_DI_TACH_SETPOINT_REACHED__SZ, REG_DI_TACH_SETPOINT_REACHED__SADDR, REG_DI_TACH_SETPOINT_REACHED__MBTABLE, REG_DI_TACH_SETPOINT_REACHED__MBPOS, REG_DI_TACH_SETPOINT_REACHED__A00, REG_DI_TACH_SETPOINT_REACHED__A01, REG_DI_TACH_SETPOINT_REACHED__A02, REG_DI_TACH_SETPOINT_REACHED__DTABLE, REG_DI_TACH_SETPOINT_REACHED__DPOS, REG_DI_TACH_SETPOINT_REACHED__RETAIN, REG_DI_TACH_SETPOINT_REACHED__STR);
    Res += REG_InitRegs(REG_DI_CNTR_VAL__GID, REG_DI_CNTR_VAL__ZONE, REG_DI_CNTR_VAL__TYPESZ, REG_DI_CNTR_VAL__GROUP, REG_DI_CNTR_VAL__TYPE, REG_DI_CNTR_VAL__POS, REG_DI_CNTR_VAL__SZ, REG_DI_CNTR_VAL__SADDR, REG_DI_CNTR_VAL__MBTABLE, REG_DI_CNTR_VAL__MBPOS, REG_DI_CNTR_VAL__A00, REG_DI_CNTR_VAL__A01, REG_DI_CNTR_VAL__A02, REG_DI_CNTR_VAL__DTABLE, REG_DI_CNTR_VAL__DPOS, REG_DI_CNTR_VAL__RETAIN, REG_DI_CNTR_VAL__STR);
    Res += REG_InitRegs(REG_DI_CNTR_SETPOINT__GID, REG_DI_CNTR_SETPOINT__ZONE, REG_DI_CNTR_SETPOINT__TYPESZ, REG_DI_CNTR_SETPOINT__GROUP, REG_DI_CNTR_SETPOINT__TYPE, REG_DI_CNTR_SETPOINT__POS, REG_DI_CNTR_SETPOINT__SZ, REG_DI_CNTR_SETPOINT__SADDR, REG_DI_CNTR_SETPOINT__MBTABLE, REG_DI_CNTR_SETPOINT__MBPOS, REG_DI_CNTR_SETPOINT__A00, REG_DI_CNTR_SETPOINT__A01, REG_DI_CNTR_SETPOINT__A02, REG_DI_CNTR_SETPOINT__DTABLE, REG_DI_CNTR_SETPOINT__DPOS, REG_DI_CNTR_SETPOINT__RETAIN, REG_DI_CNTR_SETPOINT__STR);
    Res += REG_InitRegs(REG_DI_CNTR_SETPOINT_ALLOW__GID, REG_DI_CNTR_SETPOINT_ALLOW__ZONE, REG_DI_CNTR_SETPOINT_ALLOW__TYPESZ, REG_DI_CNTR_SETPOINT_ALLOW__GROUP, REG_DI_CNTR_SETPOINT_ALLOW__TYPE, REG_DI_CNTR_SETPOINT_ALLOW__POS, REG_DI_CNTR_SETPOINT_ALLOW__SZ, REG_DI_CNTR_SETPOINT_ALLOW__SADDR, REG_DI_CNTR_SETPOINT_ALLOW__MBTABLE, REG_DI_CNTR_SETPOINT_ALLOW__MBPOS, REG_DI_CNTR_SETPOINT_ALLOW__A00, REG_DI_CNTR_SETPOINT_ALLOW__A01, REG_DI_CNTR_SETPOINT_ALLOW__A02, REG_DI_CNTR_SETPOINT_ALLOW__DTABLE, REG_DI_CNTR_SETPOINT_ALLOW__DPOS, REG_DI_CNTR_SETPOINT_ALLOW__RETAIN, REG_DI_CNTR_SETPOINT_ALLOW__STR);
    Res += REG_InitRegs(REG_DI_CNTR_SETPOINT_REACHED__GID, REG_DI_CNTR_SETPOINT_REACHED__ZONE, REG_DI_CNTR_SETPOINT_REACHED__TYPESZ, REG_DI_CNTR_SETPOINT_REACHED__GROUP, REG_DI_CNTR_SETPOINT_REACHED__TYPE, REG_DI_CNTR_SETPOINT_REACHED__POS, REG_DI_CNTR_SETPOINT_REACHED__SZ, REG_DI_CNTR_SETPOINT_REACHED__SADDR, REG_DI_CNTR_SETPOINT_REACHED__MBTABLE, REG_DI_CNTR_SETPOINT_REACHED__MBPOS, REG_DI_CNTR_SETPOINT_REACHED__A00, REG_DI_CNTR_SETPOINT_REACHED__A01, REG_DI_CNTR_SETPOINT_REACHED__A02, REG_DI_CNTR_SETPOINT_REACHED__DTABLE, REG_DI_CNTR_SETPOINT_REACHED__DPOS, REG_DI_CNTR_SETPOINT_REACHED__RETAIN, REG_DI_CNTR_SETPOINT_REACHED__STR);
    Res += REG_InitRegs(REG_DI_MODE__GID, REG_DI_MODE__ZONE, REG_DI_MODE__TYPESZ, REG_DI_MODE__GROUP, REG_DI_MODE__TYPE, REG_DI_MODE__POS, REG_DI_MODE__SZ, REG_DI_MODE__SADDR, REG_DI_MODE__MBTABLE, REG_DI_MODE__MBPOS, REG_DI_MODE__A00, REG_DI_MODE__A01, REG_DI_MODE__A02, REG_DI_MODE__DTABLE, REG_DI_MODE__DPOS, REG_DI_MODE__RETAIN, REG_DI_MODE__STR);
    Res += REG_InitRegs(REG_DI_RESET__GID, REG_DI_RESET__ZONE, REG_DI_RESET__TYPESZ, REG_DI_RESET__GROUP, REG_DI_RESET__TYPE, REG_DI_RESET__POS, REG_DI_RESET__SZ, REG_DI_RESET__SADDR, REG_DI_RESET__MBTABLE, REG_DI_RESET__MBPOS, REG_DI_RESET__A00, REG_DI_RESET__A01, REG_DI_RESET__A02, REG_DI_RESET__DTABLE, REG_DI_RESET__DPOS, REG_DI_RESET__RETAIN, REG_DI_RESET__STR);
    Res += REG_InitRegs(REG_DI_STATUS__GID, REG_DI_STATUS__ZONE, REG_DI_STATUS__TYPESZ, REG_DI_STATUS__GROUP, REG_DI_STATUS__TYPE, REG_DI_STATUS__POS, REG_DI_STATUS__SZ, REG_DI_STATUS__SADDR, REG_DI_STATUS__MBTABLE, REG_DI_STATUS__MBPOS, REG_DI_STATUS__A00, REG_DI_STATUS__A01, REG_DI_STATUS__A02, REG_DI_STATUS__DTABLE, REG_DI_STATUS__DPOS, REG_DI_STATUS__RETAIN, REG_DI_STATUS__STR);
    Res += REG_InitRegs(REG_DI_FILTER_DELAY__GID, REG_DI_FILTER_DELAY__ZONE, REG_DI_FILTER_DELAY__TYPESZ, REG_DI_FILTER_DELAY__GROUP, REG_DI_FILTER_DELAY__TYPE, REG_DI_FILTER_DELAY__POS, REG_DI_FILTER_DELAY__SZ, REG_DI_FILTER_DELAY__SADDR, REG_DI_FILTER_DELAY__MBTABLE, REG_DI_FILTER_DELAY__MBPOS, REG_DI_FILTER_DELAY__A00, REG_DI_FILTER_DELAY__A01, REG_DI_FILTER_DELAY__A02, REG_DI_FILTER_DELAY__DTABLE, REG_DI_FILTER_DELAY__DPOS, REG_DI_FILTER_DELAY__RETAIN, REG_DI_FILTER_DELAY__STR);

    //DO
    Res += REG_InitRegs(REG_DO_NORM_VAL__GID, REG_DO_NORM_VAL__ZONE, REG_DO_NORM_VAL__TYPESZ, REG_DO_NORM_VAL__GROUP, REG_DO_NORM_VAL__TYPE, REG_DO_NORM_VAL__POS, REG_DO_NORM_VAL__SZ, REG_DO_NORM_VAL__SADDR, REG_DO_NORM_VAL__MBTABLE, REG_DO_NORM_VAL__MBPOS, REG_DO_NORM_VAL__A00, REG_DO_NORM_VAL__A01, REG_DO_NORM_VAL__A02, REG_DO_NORM_VAL__DTABLE, REG_DO_NORM_VAL__DPOS, REG_DO_NORM_VAL__RETAIN, REG_DO_NORM_VAL__STR);
    Res += REG_InitRegs(REG_DO_FAST_VAL__GID, REG_DO_FAST_VAL__ZONE, REG_DO_FAST_VAL__TYPESZ, REG_DO_FAST_VAL__GROUP, REG_DO_FAST_VAL__TYPE, REG_DO_FAST_VAL__POS, REG_DO_FAST_VAL__SZ, REG_DO_FAST_VAL__SADDR, REG_DO_FAST_VAL__MBTABLE, REG_DO_FAST_VAL__MBPOS, REG_DO_FAST_VAL__A00, REG_DO_FAST_VAL__A01, REG_DO_FAST_VAL__A02, REG_DO_FAST_VAL__DTABLE, REG_DO_FAST_VAL__DPOS, REG_DO_FAST_VAL__RETAIN, REG_DO_FAST_VAL__STR);
    Res += REG_InitRegs(REG_DO_PWM_VAL__GID, REG_DO_PWM_VAL__ZONE, REG_DO_PWM_VAL__TYPESZ, REG_DO_PWM_VAL__GROUP, REG_DO_PWM_VAL__TYPE, REG_DO_PWM_VAL__POS, REG_DO_PWM_VAL__SZ, REG_DO_PWM_VAL__SADDR, REG_DO_PWM_VAL__MBTABLE, REG_DO_PWM_VAL__MBPOS, REG_DO_PWM_VAL__A00, REG_DO_PWM_VAL__A01, REG_DO_PWM_VAL__A02, REG_DO_PWM_VAL__DTABLE, REG_DO_PWM_VAL__DPOS, REG_DO_PWM_VAL__RETAIN, REG_DO_PWM_VAL__STR);
    Res += REG_InitRegs(REG_DO_PWM_ALLOW__GID, REG_DO_PWM_ALLOW__ZONE, REG_DO_PWM_ALLOW__TYPESZ, REG_DO_PWM_ALLOW__GROUP, REG_DO_PWM_ALLOW__TYPE, REG_DO_PWM_ALLOW__POS, REG_DO_PWM_ALLOW__SZ, REG_DO_PWM_ALLOW__SADDR, REG_DO_PWM_ALLOW__MBTABLE, REG_DO_PWM_ALLOW__MBPOS, REG_DO_PWM_ALLOW__A00, REG_DO_PWM_ALLOW__A01, REG_DO_PWM_ALLOW__A02, REG_DO_PWM_ALLOW__DTABLE, REG_DO_PWM_ALLOW__DPOS, REG_DO_PWM_ALLOW__RETAIN, REG_DO_PWM_ALLOW__STR);
    Res += REG_InitRegs(REG_DO_PWM_PERIOD__GID, REG_DO_PWM_PERIOD__ZONE, REG_DO_PWM_PERIOD__TYPESZ, REG_DO_PWM_PERIOD__GROUP, REG_DO_PWM_PERIOD__TYPE, REG_DO_PWM_PERIOD__POS, REG_DO_PWM_PERIOD__SZ, REG_DO_PWM_PERIOD__SADDR, REG_DO_PWM_PERIOD__MBTABLE, REG_DO_PWM_PERIOD__MBPOS, REG_DO_PWM_PERIOD__A00, REG_DO_PWM_PERIOD__A01, REG_DO_PWM_PERIOD__A02, REG_DO_PWM_PERIOD__DTABLE, REG_DO_PWM_PERIOD__DPOS, REG_DO_PWM_PERIOD__RETAIN, REG_DO_PWM_PERIOD__STR);
    Res += REG_InitRegs(REG_DO_MODE__GID, REG_DO_MODE__ZONE, REG_DO_MODE__TYPESZ, REG_DO_MODE__GROUP, REG_DO_MODE__TYPE, REG_DO_MODE__POS, REG_DO_MODE__SZ, REG_DO_MODE__SADDR, REG_DO_MODE__MBTABLE, REG_DO_MODE__MBPOS, REG_DO_MODE__A00, REG_DO_MODE__A01, REG_DO_MODE__A02, REG_DO_MODE__DTABLE, REG_DO_MODE__DPOS, REG_DO_MODE__RETAIN, REG_DO_MODE__STR);
    Res += REG_InitRegs(REG_DO_STATUS__GID, REG_DO_STATUS__ZONE, REG_DO_STATUS__TYPESZ, REG_DO_STATUS__GROUP, REG_DO_STATUS__TYPE, REG_DO_STATUS__POS, REG_DO_STATUS__SZ, REG_DO_STATUS__SADDR, REG_DO_STATUS__MBTABLE, REG_DO_STATUS__MBPOS, REG_DO_STATUS__A00, REG_DO_STATUS__A01, REG_DO_STATUS__A02, REG_DO_STATUS__DTABLE, REG_DO_STATUS__DPOS, REG_DO_STATUS__RETAIN, REG_DO_STATUS__STR);

    //AI
    Res += REG_InitRegs(REG_AI_VAL__GID, REG_AI_VAL__ZONE, REG_AI_VAL__TYPESZ, REG_AI_VAL__GROUP, REG_AI_VAL__TYPE, REG_AI_VAL__POS, REG_AI_VAL__SZ, REG_AI_VAL__SADDR, REG_AI_VAL__MBTABLE, REG_AI_VAL__MBPOS, REG_AI_VAL__A00, REG_AI_VAL__A01, REG_AI_VAL__A02, REG_AI_VAL__DTABLE, REG_AI_VAL__DPOS, REG_AI_VAL__RETAIN, REG_AI_VAL__STR);
    Res += REG_InitRegs(REG_AI_MODE__GID, REG_AI_MODE__ZONE, REG_AI_MODE__TYPESZ, REG_AI_MODE__GROUP, REG_AI_MODE__TYPE, REG_AI_MODE__POS, REG_AI_MODE__SZ, REG_AI_MODE__SADDR, REG_AI_MODE__MBTABLE, REG_AI_MODE__MBPOS, REG_AI_MODE__A00, REG_AI_MODE__A01, REG_AI_MODE__A02, REG_AI_MODE__DTABLE, REG_AI_MODE__DPOS, REG_AI_MODE__RETAIN, REG_AI_MODE__STR);
    Res += REG_InitRegs(REG_AI_STATUS__GID, REG_AI_STATUS__ZONE, REG_AI_STATUS__TYPESZ, REG_AI_STATUS__GROUP, REG_AI_STATUS__TYPE, REG_AI_STATUS__POS, REG_AI_STATUS__SZ, REG_AI_STATUS__SADDR, REG_AI_STATUS__MBTABLE, REG_AI_STATUS__MBPOS, REG_AI_STATUS__A00, REG_AI_STATUS__A01, REG_AI_STATUS__A02, REG_AI_STATUS__DTABLE, REG_AI_STATUS__DPOS, REG_AI_STATUS__RETAIN, REG_AI_STATUS__STR);
    Res += REG_InitRegs(REG_AI_KA__GID, REG_AI_KA__ZONE, REG_AI_KA__TYPESZ, REG_AI_KA__GROUP, REG_AI_KA__TYPE, REG_AI_KA__POS, REG_AI_KA__SZ, REG_AI_KA__SADDR, REG_AI_KA__MBTABLE, REG_AI_KA__MBPOS, REG_AI_KA__A00, REG_AI_KA__A01, REG_AI_KA__A02, REG_AI_KA__DTABLE, REG_AI_KA__DPOS, REG_AI_KA__RETAIN, REG_AI_KA__STR);
    Res += REG_InitRegs(REG_AI_KB__GID, REG_AI_KB__ZONE, REG_AI_KB__TYPESZ, REG_AI_KB__GROUP, REG_AI_KB__TYPE, REG_AI_KB__POS, REG_AI_KB__SZ, REG_AI_KB__SADDR, REG_AI_KB__MBTABLE, REG_AI_KB__MBPOS, REG_AI_KB__A00, REG_AI_KB__A01, REG_AI_KB__A02, REG_AI_KB__DTABLE, REG_AI_KB__DPOS, REG_AI_KB__RETAIN, REG_AI_KB__STR);

    //SYS
    Res += REG_InitRegs(REG_SYS_STAT__GID, REG_SYS_STAT__ZONE, REG_SYS_STAT__TYPESZ, REG_SYS_STAT__GROUP, REG_SYS_STAT__TYPE, REG_SYS_STAT__POS, REG_SYS_STAT__SZ, REG_SYS_STAT__SADDR, REG_SYS_STAT__MBTABLE, REG_SYS_STAT__MBPOS, REG_SYS_STAT__A00, REG_SYS_STAT__A01, REG_SYS_STAT__A02, REG_SYS_STAT__DTABLE, REG_SYS_STAT__DPOS, REG_SYS_STAT__RETAIN, 0);
    Res += REG_InitRegs(REG_SYS_SET__GID, REG_SYS_SET__ZONE, REG_SYS_SET__TYPESZ, REG_SYS_SET__GROUP, REG_SYS_SET__TYPE, REG_SYS_SET__POS, REG_SYS_SET__SZ, REG_SYS_SET__SADDR, REG_SYS_SET__MBTABLE, REG_SYS_SET__MBPOS, REG_SYS_SET__A00, REG_SYS_SET__A01, REG_SYS_SET__A02, REG_SYS_SET__DTABLE, REG_SYS_SET__DPOS, REG_SYS_SET__RETAIN, 0);
    Res += REG_InitRegs(REG_SYS_CMD__GID, REG_SYS_CMD__ZONE, REG_SYS_CMD__TYPESZ, REG_SYS_CMD__GROUP, REG_SYS_CMD__TYPE, REG_SYS_CMD__POS, REG_SYS_CMD__SZ, REG_SYS_CMD__SADDR, REG_SYS_CMD__MBTABLE, REG_SYS_CMD__MBPOS, REG_SYS_CMD__A00, REG_SYS_CMD__A01, REG_SYS_CMD__A02, REG_SYS_CMD__DTABLE, REG_SYS_CMD__DPOS, REG_SYS_CMD__RETAIN, 0);

    //USER_DATA
    Res += REG_InitRegs(REG_USER_DATA1__GID, REG_USER_DATA1__ZONE, REG_USER_DATA1__TYPESZ, REG_USER_DATA1__GROUP, REG_USER_DATA1__TYPE, REG_USER_DATA1__POS, REG_USER_DATA1__SZ, REG_USER_DATA1__SADDR, REG_USER_DATA1__MBTABLE, REG_USER_DATA1__MBPOS, REG_USER_DATA1__A00, REG_USER_DATA1__A01, REG_USER_DATA1__A02, REG_USER_DATA1__DTABLE, REG_USER_DATA1__DPOS, REG_USER_DATA1__RETAIN, REG_USER_DATA1__STR);
    Res += REG_InitRegs(REG_USER_DATA2__GID, REG_USER_DATA2__ZONE, REG_USER_DATA2__TYPESZ, REG_USER_DATA2__GROUP, REG_USER_DATA2__TYPE, REG_USER_DATA2__POS, REG_USER_DATA2__SZ, REG_USER_DATA2__SADDR, REG_USER_DATA2__MBTABLE, REG_USER_DATA2__MBPOS, REG_USER_DATA2__A00, REG_USER_DATA2__A01, REG_USER_DATA2__A02, REG_USER_DATA2__DTABLE, REG_USER_DATA2__DPOS, REG_USER_DATA2__RETAIN, REG_USER_DATA2__STR);

#ifdef DEBUG_LOG_REG
    DebugLog("MbTables: C=%d-%d D=%d-%d H=%d-%d I=%d-%d\n", MBRTU_COIL_START, MBRTU_COIL_END, MBRTU_DISC_START, MBRTU_DISC_END, MBRTU_HOLD_START, MBRTU_HOLD_END, MBRTU_INPT_START, MBRTU_INPT_END);
#endif // DEBUG_LOG_REG

    return (Res);
}

#ifdef RTE_MOD_APP
/** @brief  Copy from Data Tables into Located variables.
 *  @param  None.
 *  @return The number of copied registers.
 */
uint16_t REG_CopyMbToApp(void)
{
    uint16_t Res = 0;

    Res += REG_CopyRegs(REG_DI_NORM_VAL__POS, REG_DI_NORM_VAL__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_DI_CNTR_VAL__POS, REG_DI_CNTR_VAL__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_DI_CNTR_SETPOINT__POS, REG_DI_CNTR_SETPOINT__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_DI_CNTR_SETPOINT_REACHED__POS, REG_DI_CNTR_SETPOINT_REACHED__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_DI_TACH_VAL__POS, REG_DI_TACH_VAL__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_DI_TACH_SETPOINT__POS, REG_DI_TACH_SETPOINT__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_DI_TACH_SETPOINT_REACHED__POS, REG_DI_TACH_SETPOINT_REACHED__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_DI_MODE__POS, REG_DI_MODE__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_DI_RESET__POS, REG_DI_RESET__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_DI_STATUS__POS, REG_DI_STATUS__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_DI_FILTER_DELAY__POS, REG_DI_FILTER_DELAY__SZ, REG_COPY_MB_TO_APP, 0);

    Res += REG_CopyRegs(REG_DO_NORM_VAL__POS, REG_DO_NORM_VAL__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_DO_FAST_VAL__POS, REG_DO_FAST_VAL__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_DO_PWM_VAL__POS, REG_DO_PWM_VAL__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_DO_PWM_ALLOW__POS, REG_DO_PWM_ALLOW__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_DO_PWM_PERIOD__POS, REG_DO_PWM_PERIOD__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_DO_MODE__POS, REG_DO_MODE__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_DO_STATUS__POS, REG_DO_STATUS__SZ, REG_COPY_MB_TO_APP, 0);

    Res += REG_CopyRegs(REG_AI_VAL__POS, REG_AI_VAL__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_AI_MODE__POS, REG_AI_MODE__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_AI_STATUS__POS, REG_AI_STATUS__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_AI_KA__POS, REG_AI_KA__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_AI_KB__POS, REG_AI_KB__SZ, REG_COPY_MB_TO_APP, 0);

    Res += REG_CopyRegs(REG_SYS_CMD__POS, REG_SYS_CMD__SZ, REG_COPY_MB_TO_APP, 0);

    Res += REG_CopyRegs(REG_USER_DATA1__POS, REG_USER_DATA1__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_USER_DATA2__POS, REG_USER_DATA2__SZ, REG_COPY_MB_TO_APP, 0);

    return (Res);
}

/** @brief  Copy from Located variables into Data Tables.
 *  @param  None.
 *  @return The number of copied registers.
 */
uint16_t REG_CopyAppToMb(void)
{
    uint16_t Res = 0;

    Res += REG_CopyRegs(REG_DI_CNTR_SETPOINT__POS, REG_DI_CNTR_SETPOINT__SZ, REG_COPY_APP_TO_MB, 0);
    Res += REG_CopyRegs(REG_DI_TACH_SETPOINT__POS, REG_DI_TACH_SETPOINT__SZ, REG_COPY_APP_TO_MB, 0);
    Res += REG_CopyRegs(REG_DI_MODE__POS, REG_DI_MODE__SZ, REG_COPY_APP_TO_MB, 0);
    Res += REG_CopyRegs(REG_DI_RESET__POS, REG_DI_RESET__SZ, REG_COPY_APP_TO_MB, 0);
    Res += REG_CopyRegs(REG_DI_FILTER_DELAY__POS, REG_DI_FILTER_DELAY__SZ, REG_COPY_APP_TO_MB, 0);

    Res += REG_CopyRegs(REG_DO_NORM_VAL__POS, REG_DO_NORM_VAL__SZ, REG_COPY_APP_TO_MB, 0);
    Res += REG_CopyRegs(REG_DO_FAST_VAL__POS, REG_DO_FAST_VAL__SZ, REG_COPY_APP_TO_MB, 0);
    Res += REG_CopyRegs(REG_DO_PWM_VAL__POS, REG_DO_PWM_VAL__SZ, REG_COPY_APP_TO_MB, 0);
    Res += REG_CopyRegs(REG_DO_PWM_ALLOW__POS, REG_DO_PWM_ALLOW__SZ, REG_COPY_APP_TO_MB, 0);
    Res += REG_CopyRegs(REG_DO_PWM_PERIOD__POS, REG_DO_PWM_PERIOD__SZ, REG_COPY_APP_TO_MB, 0);
    Res += REG_CopyRegs(REG_DO_MODE__POS, REG_DO_MODE__SZ, REG_COPY_APP_TO_MB, 0);

    Res += REG_CopyRegs(REG_AI_MODE__POS, REG_AI_MODE__SZ, REG_COPY_APP_TO_MB, 0);
    Res += REG_CopyRegs(REG_AI_KA__POS, REG_AI_KA__SZ, REG_COPY_APP_TO_MB, 0);
    Res += REG_CopyRegs(REG_AI_KB__POS, REG_AI_KB__SZ, REG_COPY_APP_TO_MB, 0);

    Res += REG_CopyRegs(REG_SYS_CMD__POS, REG_SYS_CMD__SZ, REG_COPY_APP_TO_MB, 0);

    Res += REG_CopyRegs(REG_USER_DATA1__POS, REG_USER_DATA1__SZ, REG_COPY_APP_TO_MB, 0);
    Res += REG_CopyRegs(REG_USER_DATA2__POS, REG_USER_DATA2__SZ, REG_COPY_APP_TO_MB, 0);

    return (Res);
}
#endif // RTE_MOD_APP


/** @brief  Set values by default.
 *  @param  None.
 *  @return None.
 */
void REG_SetDef(void)
{
	uint8_t  BuffBy;
    uint16_t BuffWo;
    uint32_t BuffDWo;
    float    BuffFlo;
    uint8_t  i;

    //DI ======================================================================
    for(i=0; i<PLC_DI_SZ; i++)
    {
        BuffBy = PLC_DI_MODE_DEF;
        REG_CopyRegByPos(REG_DI_MODE__POS+i, REG_COPY_VAR_TO_MB__NO_MON, &BuffBy);

        BuffBy = PLC_DI_TACH_SETPOINT_ALLOW_DEF;
        REG_CopyRegByPos(REG_DI_TACH_SETPOINT_ALLOW__POS+i, REG_COPY_VAR_TO_MB__NO_MON, &BuffBy);

        BuffBy = PLC_DI_CNTR_SETPOINT_ALLOW_DEF;
        REG_CopyRegByPos(REG_DI_CNTR_SETPOINT_ALLOW__POS+i, REG_COPY_VAR_TO_MB__NO_MON, &BuffBy);

        BuffDWo = PLC_DI_FLTR_DELAY_DEF;
        REG_CopyRegByPos(REG_DI_FILTER_DELAY__POS+i, REG_COPY_VAR_TO_MB__NO_MON, &BuffDWo);
    }

    //DO ======================================================================
    for(i=0; i<PLC_DO_SZ; i++)
    {
        BuffBy = PLC_DO_MODE_DEF;
        REG_CopyRegByPos(REG_DO_MODE__POS+i, REG_COPY_VAR_TO_MB__NO_MON, &BuffBy);

        BuffFlo = PLC_DO_PWM_T_DEF;
        REG_CopyRegByPos(REG_DO_PWM_PERIOD__POS+i, REG_COPY_VAR_TO_MB__NO_MON, &BuffFlo);

        BuffFlo = PLC_DO_PWM_D_DEF;
        REG_CopyRegByPos(REG_DO_PWM_VAL__POS+i, REG_COPY_VAR_TO_MB__NO_MON, &BuffFlo);

        BuffBy = PLC_DO_PWM_ALLOW_DEF;
        REG_CopyRegByPos(REG_DO_PWM_ALLOW__POS+i, REG_COPY_VAR_TO_MB__NO_MON, &BuffBy);

        BuffBy = PLC_DO_NORM_VAL_DEF;
        REG_CopyRegByPos(REG_DO_NORM_VAL__POS+i, REG_COPY_VAR_TO_MB__NO_MON, &BuffBy);

        BuffBy = PLC_DO_FAST_VAL_DEF;
        REG_CopyRegByPos(REG_DO_FAST_VAL__POS+i, REG_COPY_VAR_TO_MB__NO_MON, &BuffBy);
    }

    //AI ======================================================================
	for(i=0; i<PLC_AI_SZ; i++)
	{
		BuffBy = PLC_AI_MODE_DEF;
		REG_CopyRegByPos(REG_AI_MODE__POS+i, REG_COPY_VAR_TO_MB__NO_MON, &BuffBy);

		BuffFlo = PLC_AI_KA_DEF;
		REG_CopyRegByPos(REG_AI_KA__POS+i, REG_COPY_VAR_TO_MB__NO_MON, &BuffFlo);

		BuffFlo = PLC_AI_KB_DEF;
		REG_CopyRegByPos(REG_AI_KB__POS+i, REG_COPY_VAR_TO_MB__NO_MON, &BuffFlo);
	}

    //SYS_STAT =================================================================
    BuffWo = PLC_HW_CODE;
    REG_CopyRegByPos(REG_SYS_STAT__POS_HW_CODE, REG_COPY_VAR_TO_MB__NO_MON, &BuffWo);

    BuffWo = (uint16_t)PLC_HW_VAR;
    REG_CopyRegByPos(REG_SYS_STAT__POS_HW_VAR, REG_COPY_VAR_TO_MB__NO_MON, &BuffWo);

    BuffWo = PLC_RTE_VERSION;
    REG_CopyRegByPos(REG_SYS_STAT__POS_RTE_VER, REG_COPY_VAR_TO_MB__NO_MON, &BuffWo);

    BuffWo = PLC_RTE_YYYY;
    REG_CopyRegByPos(REG_SYS_STAT__POS_RTE_YYYY, REG_COPY_VAR_TO_MB__NO_MON, &BuffWo);

    BuffWo = PLC_RTE_DDMM;
    REG_CopyRegByPos(REG_SYS_STAT__POS_RTE_DDMM, REG_COPY_VAR_TO_MB__NO_MON, &BuffWo);
}


/** @brief  Set register SYS_STAT1.
 *  @param  FieldIn - field number:
 *  @arg    = PLC_SYS_STAT1_APP_INITED ... PLC_SYS_STAT1_LED_USER
 *  @param  ValueIn - field value:
 *  @arg    = BIT_FALSE
 *  @arg    = BIT_TRUE
 *  @return None.
 */
void REG_SYS_STAT1_Set(uint8_t FieldIn, uint8_t ValueIn)
{
	uint8_t Value = ((ValueIn) ? BIT_TRUE : BIT_FALSE);

	switch(FieldIn)
	{
		case PLC_SYS_STAT1_APP_INITED:
			PLC_SYS_STAT1.Pack.AppInited = Value;
#ifdef DEBUG_LOG_SYS_REG
			DebugLog("PLC_SYS_STAT1.Pack.AppInited=%d\n", PLC_SYS_STAT1.Pack.AppInited);
#endif // DEBUG_LOG_SYS_REG
			break;

		case PLC_SYS_STAT1_APP_RUN:
			PLC_SYS_STAT1.Pack.AppRun = Value;
#ifdef DEBUG_LOG_SYS_REG
			DebugLog("PLC_SYS_STAT1.Pack.AppRun=%d\n", PLC_SYS_STAT1.Pack.AppRun);
#endif // DEBUG_LOG_SYS_REG
			break;

		case PLC_SYS_STAT1_APP_RUN1:
			PLC_SYS_STAT1.Pack.AppRun1 = Value;
#ifdef DEBUG_LOG_SYS_REG
			DebugLog("PLC_SYS_STAT1.Pack.AppRun=%d\n", PLC_SYS_STAT1.Pack.AppRun);
#endif // DEBUG_LOG_SYS_REG
			break;

		case PLC_SYS_STAT1_SFTY_TIM_SET:
			PLC_SYS_STAT1.Pack.SftyTimSet = Value;
#ifdef DEBUG_LOG_SYS_REG
			DebugLog("PLC_SYS_STAT1.Pack.SftyTimSet=%d\n", PLC_SYS_STAT1.Pack.SftyTimSet);
#endif // DEBUG_LOG_SYS_REG
			break;

		case PLC_SYS_STAT1_SFTY_TIM_CPLT:
			PLC_SYS_STAT1.Pack.SftyTimCplt = Value;
#ifdef DEBUG_LOG_SYS_REG
			DebugLog("PLC_SYS_STAT1.Pack.SftyTimCplt=%d\n", PLC_SYS_STAT1.Pack.SftyTimCplt);
#endif // DEBUG_LOG_SYS_REG
			break;

		case PLC_SYS_STAT1_WD_TIM_SET:
			PLC_SYS_STAT1.Pack.WdTimSet = Value;
#ifdef DEBUG_LOG_SYS_REG
			DebugLog("PLC_SYS_STAT1.Pack.WdTimSet=%d\n", PLC_SYS_STAT1.Pack.WdTimSet);
#endif // DEBUG_LOG_SYS_REG
			break;

		case PLC_SYS_STAT1_LED_USER:
			PLC_SYS_STAT1.Pack.LedUser = Value;
#ifdef DEBUG_LOG_SYS_REG
			DebugLog("PLC_SYS_STAT1.Pack.LedUser=%d\n", PLC_SYS_STAT1.Pack.LedUser);
#endif // DEBUG_LOG_SYS_REG
			break;
	}

	REG_CopyRegByPos(REG_SYS_STAT__POS_STAT1, REG_COPY_VAR_TO_MB__NO_MON, &PLC_SYS_STAT1.Data);
}
